[book]
title = "Samuel Galvão Elias – Curriculum Vitae"
description = "Curriculum Vitae of Samuel Galvão Elias – Microbiology, Mycology and Bioinformatics"
authors = ["Samuel Galvão Elias <sgelias@outlook.com>"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false
use-default-preprocessors = true

[preprocessor.gettext]
after = ["links"]

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = false
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]
no-section-label = true
git-repository-url = "https://github.com/sgelias/cv"
site-url = "/cv/"

[output.html.print]
enable = true
page-break = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.fold]
enable = false
level = 0
